# Generated by Django 6.0.7 on 2026-08-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksite',
            name='spend',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
    ]
