# Generated by Django 6.0.7 on 2026-08-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksites', '0002_worksite_spend'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksite',
            name='client_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
    ]
