# Generated by Django 6.0.7 on 2026-08-03 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksites', '0003_worksite_client_paid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorksiteDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('permit', 'Building Permit'), ('drawing', 'Approved Drawing'), ('photo', 'Site Photo'), ('agreement', 'Agreement / Contract'), ('boq', 'BOQ (Bill of Quantities)'), ('invoice', 'Material Invoice'), ('other', 'Other Attachment')], default='other', max_length=32)),
                ('file', models.FileField(upload_to='worksites/documents/')),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
                ('worksite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='worksites.worksite')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
