# Generated by Django 6.0.7 on 2026-08-01 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('salaries', '0002_salary_status_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='salary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='salaries.salaryrecord'),
        ),
    ]
