# Generated by Django 6.0.7 on 2026-08-02 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_remove_employee_email_alter_employee_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='id_photo',
            field=models.FileField(blank=True, null=True, upload_to='employee_ids/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='employee_photos/'),
        ),
    ]
