# Generated by Django 6.0.7 on 2026-08-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employee_id_photo_employee_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('On Leave', 'On Leave'), ('Inactive', 'Inactive')], db_index=True, default='Active', max_length=20),
        ),
    ]
