# Generated by Django 6.0.7 on 2026-08-02 17:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('worksites', '0002_worksite_spend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Fuel', 'Fuel'), ('Machinery Rental', 'Machinery Rental'), ('Utilities', 'Utilities'), ('Safety Gear', 'Safety Gear'), ('Permits', 'Permits')], default='Fuel', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('worksite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='worksites.worksite')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
