# Generated by Django 6.0.7 on 2026-08-02 08:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employee_id_photo_employee_photo'),
        ('salaries', '0002_salary_status_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salaryrecord',
            options={'ordering': ['-week_end_date', '-year', '-month', 'employee__name']},
        ),
        migrations.RemoveConstraint(
            model_name='salaryrecord',
            name='unique_employee_salary_period',
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='week_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salaryrecord',
            name='month',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='salaryrecord',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2000)]),
        ),
        migrations.AddConstraint(
            model_name='salaryrecord',
            constraint=models.UniqueConstraint(fields=('employee', 'week_end_date'), name='unique_employee_weekly_salary_period'),
        ),
    ]
