# Generated by Django 6.0.7 on 2026-08-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_employee_is_archived_alter_employee_status'),
        ('salaries', '0003_alter_salaryrecord_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='salaryrecord',
            index=models.Index(fields=['week_end_date'], name='salary_week_end_idx'),
        ),
        migrations.AddIndex(
            model_name='salaryrecord',
            index=models.Index(fields=['week_end_date', 'status'], name='salary_week_status_idx'),
        ),
    ]
