# Generated by Django 6.0.7 on 2026-08-05 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0004_salaryrecord_salary_week_end_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryrecord',
            name='present_days',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7),
        ),
    ]
