# Generated by Django 6.0.7 on 2026-08-01 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('worksites', '0002_worksite_spend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('supplier', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('Delivered', 'Delivered'), ('Ordered', 'Ordered'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('worksite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='worksites.worksite')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
