# Generated by Django 6.0.7 on 2026-08-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_materialcatalog_material_catalog_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='used_quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
