# Generated by Django 6.0.7 on 2026-08-04 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_material_used_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='used_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
