# Generated by Django 6.0.7 on 2026-08-04 02:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_alter_material_used_quantity'),
        ('worksites', '0005_clientpayment_dailysitelog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='material',
            name='status',
        ),
        migrations.RemoveField(
            model_name='material',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='material',
            name='used_quantity',
        ),
        migrations.RemoveField(
            model_name='material',
            name='worksite',
        ),
        migrations.CreateModel(
            name='MaterialDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('Delivered', 'Delivered'), ('Ordered', 'Ordered'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('delivery_date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('worksite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='worksites.worksite')),
            ],
            options={
                'ordering': ['-delivery_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='material',
            name='delivery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='materials.materialdelivery'),
            preserve_default=False,
        ),
    ]
