# Generated by Django 6.0.7 on 2026-08-04 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_alter_material_options_remove_material_status_and_more'),
        ('worksites', '0005_clientpayment_dailysitelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteStockUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=20)),
                ('used_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('worksite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_usages', to='worksites.worksite')),
            ],
            options={
                'ordering': ['-logged_at'],
            },
        ),
    ]
