# Generated by Django 6.0.7 on 2026-08-04 18:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('worksites', '0005_clientpayment_dailysitelog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcontract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor_name', models.CharField(max_length=150)),
                ('trade', models.CharField(choices=[('electrical', 'Electrical Work'), ('plumbing', 'Plumbing & Sanitary'), ('tiling', 'Tiling & Flooring'), ('painting', 'Painting & Polishing'), ('interior', 'Interior & Woodwork'), ('roofing', 'Roofing & Steel Structure'), ('false_ceiling', 'Gypsum & False Ceiling'), ('masonry', 'Masonry & Concrete'), ('other', 'Other Subcontract')], default='other', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('contract_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold')], default='in_progress', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('worksite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcontracts', to='worksites.worksite')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubcontractPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('upi', 'UPI')], default='bank_transfer', max_length=30)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcontract_payments', to=settings.AUTH_USER_MODEL)),
                ('subcontract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subcontracts.subcontract')),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
