# Generated by Django 6.0.7 on 2026-08-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcontracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcontract',
            name='phone',
            field=models.CharField(blank=True, help_text='Subcontractor contact phone number for WhatsApp receipts', max_length=20),
        ),
    ]
