# Generated by Django 6.0.7 on 2026-08-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_remove_attendance_check_in_and_more'),
        ('employees', '0007_alter_employee_is_archived_alter_employee_status'),
        ('worksites', '0005_clientpayment_dailysitelog'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date'], name='attendance_date_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date', 'status'], name='attendance_date_status_idx'),
        ),
    ]
