# Generated by Django 6.0.7 on 2026-08-05 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendance_attendance_date_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='Extra overtime hours worked', max_digits=4),
        ),
    ]
